---
title: Philip Bloemendal Prijs
timezone: Europe/Amsterdam
collections:
  posts:
    title: Nieuws
    output: true
  winners:
    title: Winnaars
    output: true
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
    photos:
    - image: 
      txt: 
    videos: []
- scope:
    path: ''
    type: posts
  values:
    layout: page
    permalink: "/artikel/:title"
    photos:
    - image: 
      txt: 
    videos: []
- scope:
    path: ''
    type: winners
  values:
    layout: page
    permalink: "/winnaar/:title"
    year: 
    photos:
    - image: 
      txt: 
    videos: []
email: bloemendalprijs@beeldengeluid.nl
description: De Philip Bloemendal Prijs stimuleert jong journalistiek presentatietalent
  in de media. Genomineerden ontvangen een oorkonde en de winnaar ontvangt tevens
  een geldbedrag van 3500 euro, te besteden aan een studie- of opleidingsproject om
  zich binnen het vakgebied verder te bekwamen.
baseurl: ''
url: https://www.bloemendal.info
twitter_username: bloemendalprijs
markdown: kramdown
excerpt_separator: "<more />"
plugins:
- jekyll-feed
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- script
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/
- ".siteleafignore"
- ".forestry/"
