backend:
  name: git-gateway
  branch: main

# publish_mode: editorial_workflow

media_folder: "_uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/uploads" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "nieuws" # Used in routes, e.g., /admin/collections/blog
    label: "Nieuws" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Foto", name: "thumbnail", widget: "image"}
      - {label: "Tekst", name: "body", widget: "markdown"}
